# Generated by Django 4.0.3 on 2022-04-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_average_solving_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../../../media/images/default_image.png', upload_to='images'),
        ),
    ]
