# Generated by Django 4.0.3 on 2022-04-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_solved_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_quizzes',
            field=models.IntegerField(default=0),
        ),
    ]
