# Generated by Django 4.0.3 on 2022-04-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_created_quizzes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../../../media/images/default_image.png', upload_to='media/images'),
        ),
    ]
