# Generated by Django 4.0.3 on 2022-04-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmasteruser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='quizmasteruser',
            name='user_permissions',
        ),
    ]
