# Generated by Django 4.0.3 on 2022-04-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_quizmasteruser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmasteruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
