# Generated by Django 4.0.3 on 2022-03-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_quiz_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
    ]
