# Generated by Django 4.0.3 on 2022-03-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_rename_text_answer_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('biology', 'Biology'), ('chemistry', 'Chemistry'), ('physics', 'Physics'), ('information technologies', 'Information Technologies'), ('math', 'Math'), ('languages', 'Languages'), ('literature', 'Literature'), ('music', 'Music'), ('art', 'Art'), ('history', 'History'), ('geography', 'Geography'), ('philosophy', 'Philosophy'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
